# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: new/top.xdc

# IP: ip/ila_3/ila_3.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==ila_3 || ORIG_REF_NAME==ila_3} -quiet] -quiet

# IP: ip/fir_compiler_0/fir_compiler_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==fir_compiler_0 || ORIG_REF_NAME==fir_compiler_0} -quiet] -quiet

# IP: ip/jesd204_phy_0/jesd204_phy_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==jesd204_phy_0 || ORIG_REF_NAME==jesd204_phy_0} -quiet] -quiet

# IP: ip/jesd204b_ad/jesd204b_ad.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==jesd204b_ad || ORIG_REF_NAME==jesd204b_ad} -quiet] -quiet
