# 
# Synthesis run script generated by Vivado
# 

set TIME_start [clock seconds] 
proc create_report { reportName command } {
  set status "."
  append status $reportName ".fail"
  if { [file exists $status] } {
    eval file delete [glob $status]
  }
  send_msg_id runtcl-4 info "Executing : $command"
  set retval [eval catch { $command } msg]
  if { $retval != 0 } {
    set fp [open $status w]
    close $fp
    send_msg_id runtcl-5 warning "$msg"
  }
}
create_project -in_memory -part xczu15eg-ffvb1156-2-i

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_msg_config -source 4 -id {IP_Flow 19-2162} -severity warning -new_severity info
set_property webtalk.parent_dir E:/01syf/00BackupAndLearning/FPGA/MY_test/FMC121_AD/FMC121_AD.cache/wt [current_project]
set_property parent.project_path E:/01syf/00BackupAndLearning/FPGA/MY_test/FMC121_AD/FMC121_AD.xpr [current_project]
set_property XPM_LIBRARIES {XPM_CDC XPM_MEMORY} [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
set_property ip_output_repo e:/01syf/00BackupAndLearning/FPGA/MY_test/FMC121_AD/FMC121_AD.cache/ip [current_project]
set_property ip_cache_permissions {read write} [current_project]
add_files E:/01syf/00BackupAndLearning/FPGA/MY_test/FMC121_AD/FMC121_AD.srcs/sources_1/lowpass_100MHz.coe
read_verilog -library xil_defaultlib {
  E:/01syf/00BackupAndLearning/FPGA/MY_test/FMC121_AD/FMC121_AD.srcs/sources_1/new/Decode.v
  E:/01syf/00BackupAndLearning/FPGA/MY_test/FMC121_AD/FMC121_AD.srcs/sources_1/new/FIR_filter.v
  E:/01syf/00BackupAndLearning/FPGA/MY_test/FMC121_AD/FMC121_AD.srcs/sources_1/new/Fifo_cache.v
  E:/01syf/00BackupAndLearning/FPGA/MY_test/FMC121_AD/FMC121_AD.srcs/sources_1/new/UART_rx.v
  E:/01syf/00BackupAndLearning/FPGA/MY_test/FMC121_AD/FMC121_AD.srcs/sources_1/new/UART_tx.v
  E:/01syf/00BackupAndLearning/FPGA/MY_test/FMC121_AD/FMC121_AD.srcs/sources_1/new/data_send.v
  E:/01syf/00BackupAndLearning/FPGA/MY_test/FMC121_AD/FMC121_AD.srcs/sources_1/new/jesd204_dac_clocking.v
  E:/01syf/00BackupAndLearning/FPGA/MY_test/FMC121_AD/FMC121_AD.srcs/sources_1/new/pulse_data.v
  E:/01syf/00BackupAndLearning/FPGA/MY_test/FMC121_AD/FMC121_AD.srcs/sources_1/new/pulse_sum.v
  E:/01syf/00BackupAndLearning/FPGA/MY_test/FMC121_AD/FMC121_AD.srcs/sources_1/new/ram_rw.v
  E:/01syf/00BackupAndLearning/FPGA/MY_test/FMC121_AD/FMC121_AD.srcs/sources_1/new/test_top.v
}
read_vhdl -library xil_defaultlib {
  E:/01syf/00BackupAndLearning/FPGA/MY_test/FMC121_AD/FMC121_AD.srcs/sources_1/new/FMC121_top.vhd
  E:/01syf/00BackupAndLearning/FPGA/MY_test/FMC121_AD/FMC121_AD.srcs/sources_1/new/ad9680.vhd
  E:/01syf/00BackupAndLearning/FPGA/MY_test/FMC121_AD/FMC121_AD.srcs/sources_1/new/hmc7044.vhd
  E:/01syf/00BackupAndLearning/FPGA/MY_test/FMC121_AD/FMC121_AD.srcs/sources_1/new/neg_data.vhd
}
read_ip -quiet E:/01syf/00BackupAndLearning/FPGA/MY_test/FMC121_AD/FMC121_AD.srcs/sources_1/ip/ila_3/ila_3.xci
set_property used_in_synthesis false [get_files -all e:/01syf/00BackupAndLearning/FPGA/MY_test/FMC121_AD/FMC121_AD.srcs/sources_1/ip/ila_3/ila_v6_2/constraints/ila_impl.xdc]
set_property used_in_implementation false [get_files -all e:/01syf/00BackupAndLearning/FPGA/MY_test/FMC121_AD/FMC121_AD.srcs/sources_1/ip/ila_3/ila_v6_2/constraints/ila_impl.xdc]
set_property used_in_implementation false [get_files -all e:/01syf/00BackupAndLearning/FPGA/MY_test/FMC121_AD/FMC121_AD.srcs/sources_1/ip/ila_3/ila_v6_2/constraints/ila.xdc]
set_property used_in_implementation false [get_files -all e:/01syf/00BackupAndLearning/FPGA/MY_test/FMC121_AD/FMC121_AD.srcs/sources_1/ip/ila_3/ila_3_ooc.xdc]

read_ip -quiet E:/01syf/00BackupAndLearning/FPGA/MY_test/FMC121_AD/FMC121_AD.srcs/sources_1/ip/fir_compiler_0/fir_compiler_0.xci
set_property used_in_implementation false [get_files -all e:/01syf/00BackupAndLearning/FPGA/MY_test/FMC121_AD/FMC121_AD.srcs/sources_1/ip/fir_compiler_0/constraints/fir_compiler_v7_2.xdc]
set_property used_in_implementation false [get_files -all e:/01syf/00BackupAndLearning/FPGA/MY_test/FMC121_AD/FMC121_AD.srcs/sources_1/ip/fir_compiler_0/fir_compiler_0_ooc.xdc]

read_ip -quiet E:/01syf/00BackupAndLearning/FPGA/MY_test/FMC121_AD/FMC121_AD.srcs/sources_1/ip/jesd204_phy_0/jesd204_phy_0.xci
set_property used_in_implementation false [get_files -all e:/01syf/00BackupAndLearning/FPGA/MY_test/FMC121_AD/FMC121_AD.srcs/sources_1/ip/jesd204_phy_0/synth/jesd204_phy_0_ooc.xdc]
set_property used_in_implementation false [get_files -all e:/01syf/00BackupAndLearning/FPGA/MY_test/FMC121_AD/FMC121_AD.srcs/sources_1/ip/jesd204_phy_0/synth/jesd204_phy_0.xdc]
set_property used_in_implementation false [get_files -all e:/01syf/00BackupAndLearning/FPGA/MY_test/FMC121_AD/FMC121_AD.srcs/sources_1/ip/jesd204_phy_0/synth/jesd204_phy_0_clock_group.xdc]
set_property used_in_implementation false [get_files -all e:/01syf/00BackupAndLearning/FPGA/MY_test/FMC121_AD/FMC121_AD.srcs/sources_1/ip/jesd204_phy_0/synth/jesd204_phy_0_clocks.xdc]
set_property used_in_implementation false [get_files -all e:/01syf/00BackupAndLearning/FPGA/MY_test/FMC121_AD/FMC121_AD.srcs/sources_1/ip/jesd204_phy_0/ip_0/synth/jesd204_phy_0_gt_ooc.xdc]
set_property used_in_implementation false [get_files -all e:/01syf/00BackupAndLearning/FPGA/MY_test/FMC121_AD/FMC121_AD.srcs/sources_1/ip/jesd204_phy_0/ip_0/synth/jesd204_phy_0_gt.xdc]

read_ip -quiet E:/01syf/00BackupAndLearning/FPGA/MY_test/FMC121_AD/FMC121_AD.srcs/sources_1/ip/jesd204b_ad/jesd204b_ad.xci
set_property used_in_implementation false [get_files -all e:/01syf/00BackupAndLearning/FPGA/MY_test/FMC121_AD/FMC121_AD.srcs/sources_1/ip/jesd204b_ad/synth/jesd204b_ad.xdc]
set_property used_in_implementation false [get_files -all e:/01syf/00BackupAndLearning/FPGA/MY_test/FMC121_AD/FMC121_AD.srcs/sources_1/ip/jesd204b_ad/synth/jesd204b_ad_ooc.xdc]

read_ip -quiet E:/01syf/00BackupAndLearning/FPGA/MY_test/FMC121_AD/FMC121_AD.srcs/sources_1/ip/sysclk/sysclk.xci
set_property used_in_implementation false [get_files -all e:/01syf/00BackupAndLearning/FPGA/MY_test/FMC121_AD/FMC121_AD.srcs/sources_1/ip/sysclk/sysclk_board.xdc]
set_property used_in_implementation false [get_files -all e:/01syf/00BackupAndLearning/FPGA/MY_test/FMC121_AD/FMC121_AD.srcs/sources_1/ip/sysclk/sysclk.xdc]
set_property used_in_implementation false [get_files -all e:/01syf/00BackupAndLearning/FPGA/MY_test/FMC121_AD/FMC121_AD.srcs/sources_1/ip/sysclk/sysclk_ooc.xdc]

read_ip -quiet E:/01syf/00BackupAndLearning/FPGA/MY_test/FMC121_AD/FMC121_AD.srcs/sources_1/ip/vio_0/vio_0.xci
set_property used_in_implementation false [get_files -all e:/01syf/00BackupAndLearning/FPGA/MY_test/FMC121_AD/FMC121_AD.srcs/sources_1/ip/vio_0/vio_0.xdc]
set_property used_in_implementation false [get_files -all e:/01syf/00BackupAndLearning/FPGA/MY_test/FMC121_AD/FMC121_AD.srcs/sources_1/ip/vio_0/vio_0_ooc.xdc]

read_ip -quiet E:/01syf/00BackupAndLearning/FPGA/MY_test/FMC121_AD/FMC121_AD.srcs/sources_1/ip/GLB_dcm/GLB_dcm.xci
set_property used_in_implementation false [get_files -all e:/01syf/00BackupAndLearning/FPGA/MY_test/FMC121_AD/FMC121_AD.srcs/sources_1/ip/GLB_dcm/GLB_dcm_board.xdc]
set_property used_in_implementation false [get_files -all e:/01syf/00BackupAndLearning/FPGA/MY_test/FMC121_AD/FMC121_AD.srcs/sources_1/ip/GLB_dcm/GLB_dcm.xdc]
set_property used_in_implementation false [get_files -all e:/01syf/00BackupAndLearning/FPGA/MY_test/FMC121_AD/FMC121_AD.srcs/sources_1/ip/GLB_dcm/GLB_dcm_ooc.xdc]

read_ip -quiet E:/01syf/00BackupAndLearning/FPGA/MY_test/FMC121_AD/FMC121_AD.srcs/sources_1/ip/blk_mem_gen_0/blk_mem_gen_0.xci
set_property used_in_implementation false [get_files -all e:/01syf/00BackupAndLearning/FPGA/MY_test/FMC121_AD/FMC121_AD.srcs/sources_1/ip/blk_mem_gen_0/blk_mem_gen_0_ooc.xdc]

read_ip -quiet E:/01syf/00BackupAndLearning/FPGA/MY_test/FMC121_AD/FMC121_AD.srcs/sources_1/ip/vio_1/vio_1.xci
set_property used_in_implementation false [get_files -all e:/01syf/00BackupAndLearning/FPGA/MY_test/FMC121_AD/FMC121_AD.srcs/sources_1/ip/vio_1/vio_1.xdc]
set_property used_in_implementation false [get_files -all e:/01syf/00BackupAndLearning/FPGA/MY_test/FMC121_AD/FMC121_AD.srcs/sources_1/ip/vio_1/vio_1_ooc.xdc]

read_ip -quiet E:/01syf/00BackupAndLearning/FPGA/MY_test/FMC121_AD/FMC121_AD.srcs/sources_1/ip/fifo_generator_0/fifo_generator_0.xci
set_property used_in_implementation false [get_files -all e:/01syf/00BackupAndLearning/FPGA/MY_test/FMC121_AD/FMC121_AD.srcs/sources_1/ip/fifo_generator_0/fifo_generator_0.xdc]
set_property used_in_implementation false [get_files -all e:/01syf/00BackupAndLearning/FPGA/MY_test/FMC121_AD/FMC121_AD.srcs/sources_1/ip/fifo_generator_0/fifo_generator_0_clocks.xdc]
set_property used_in_implementation false [get_files -all e:/01syf/00BackupAndLearning/FPGA/MY_test/FMC121_AD/FMC121_AD.srcs/sources_1/ip/fifo_generator_0/fifo_generator_0_ooc.xdc]

# Mark all dcp files as not used in implementation to prevent them from being
# stitched into the results of this synthesis run. Any black boxes in the
# design are intentionally left as such for best results. Dcp files will be
# stitched into the design at a later time, either when this synthesis run is
# opened, or when it is stitched into a dependent implementation run.
foreach dcp [get_files -quiet -all -filter file_type=="Design\ Checkpoint"] {
  set_property used_in_implementation false $dcp
}
read_xdc E:/01syf/00BackupAndLearning/FPGA/MY_test/FMC121_AD/FMC121_AD.srcs/constrs_1/new/top.xdc
set_property used_in_implementation false [get_files E:/01syf/00BackupAndLearning/FPGA/MY_test/FMC121_AD/FMC121_AD.srcs/constrs_1/new/top.xdc]

read_xdc dont_touch.xdc
set_property used_in_implementation false [get_files dont_touch.xdc]
set_param ips.enableIPCacheLiteLoad 1
close [open __synthesis_is_running__ w]

synth_design -top test_top -part xczu15eg-ffvb1156-2-i


# disable binary constraint mode for synth run checkpoints
set_param constraints.enableBinaryConstraints false
write_checkpoint -force -noxdef test_top.dcp
create_report "synth_1_synth_report_utilization_0" "report_utilization -file test_top_utilization_synth.rpt -pb test_top_utilization_synth.pb"
file delete __synthesis_is_running__
close [open __synthesis_is_complete__ w]
