# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: H:/ZynqUltralScaleXCZU15EG/FMC121_AD/FMC121_AD.srcs/sources_1/ip/GLB_dcm/GLB_dcm.xci
# IP: The module: 'GLB_dcm' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: h:/ZynqUltralScaleXCZU15EG/FMC121_AD/FMC121_AD.srcs/sources_1/ip/GLB_dcm/GLB_dcm_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'GLB_dcm'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# XDC: h:/ZynqUltralScaleXCZU15EG/FMC121_AD/FMC121_AD.srcs/sources_1/ip/GLB_dcm/GLB_dcm.xdc
# XDC: The top module name and the constraint reference have the same name: 'GLB_dcm'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# XDC: h:/ZynqUltralScaleXCZU15EG/FMC121_AD/FMC121_AD.srcs/sources_1/ip/GLB_dcm/GLB_dcm_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'GLB_dcm'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# IP: H:/ZynqUltralScaleXCZU15EG/FMC121_AD/FMC121_AD.srcs/sources_1/ip/GLB_dcm/GLB_dcm.xci
# IP: The module: 'GLB_dcm' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: h:/ZynqUltralScaleXCZU15EG/FMC121_AD/FMC121_AD.srcs/sources_1/ip/GLB_dcm/GLB_dcm_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'GLB_dcm'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# XDC: h:/ZynqUltralScaleXCZU15EG/FMC121_AD/FMC121_AD.srcs/sources_1/ip/GLB_dcm/GLB_dcm.xdc
# XDC: The top module name and the constraint reference have the same name: 'GLB_dcm'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# XDC: h:/ZynqUltralScaleXCZU15EG/FMC121_AD/FMC121_AD.srcs/sources_1/ip/GLB_dcm/GLB_dcm_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'GLB_dcm'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet
